### ISSUE TITLE
HMR not working with .dist in dev

### ISSUE THREAD

**Issue by AleksandarDev** [pueue/nextjs-typescript-boilerplate#1]
I'm on Windows 10 and hot reload is not working with symbols in path for me.

**Comment by AleksandarDev** [comment]
Because `.dist` conflicts with ignoring all (dot) items

https://github.com/zeit/next.js/pull/1307

I would suggest using `dist` instead

**Comment by kdby-io** [comment]
@AleksandarDev Thank you!
